# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

# Commands to be run before your environment runs.
before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --prefer-source --no-interaction


# Commands you want to run that will verify your build.
#script: phpunit --configuration phpunit.xml --coverage-text Tests/testObjectGet.php
script: phpunit --configuration build/phpunit.xml --testsuite All
# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0
    - php: 7.1
    - php: 7.2


# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
